---
# tasks file for first
#- name: Set authorized key taken from file
#  authorized_key:
#    user: "{{ item }}"
#    state: present
#    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXbwrytwzUclzyn3hgnQEauBp233hFW9oA5xb/SL1UqGzRXE3H6DFlcahdOL0jklBeS/AirpAZJ47YVs8jdX4bzoBUXIzgbMabNeYK5DFob+hGw70j9IOJ0VcEApoPMpzkckwzdzTjYgUKicpa6gMguRNK/lmkUCpebTE8O2z5zF9SiQ/Ce1Xws3afAnuXqcpSD9IxNKdrA1csrITFk1HwV+3ii7+DIl7FZf5tpPLypsTVGgM4yDKN6bxF/9KYfcdXGIhYwU7AUyuGj5ucssMBFexb9Pc2Q1XhTFGTFotRMr7h50HchGNG+ugImbyhXIhZmrGGiA1oPTtn+/3lujYJz6TJHxO9VFXjWrWB9heqt59uJoim5ekosDew3sp7y8FxM1U3HcDnX/qkyI5qHPa/e2iQfJcxcvRNTtIk2p/Sp/xxOIpwAVEJesvUjn6A4deMnliWlKA6qvHKvn9X0duHKYB44+XZ9YzgDH3Bzt00iiux1En0795jq0H0qGTdAM/poJ4sG8Vr9r1fxOZ69ZU0ZYLUjiHBggjRyimq0EpJvw7UlPE7oTusWgDxUfirOKB9w13aIogoTwLTzxjo9Vdtd9l7WaQWgzNVYLvTRdpFOa5ZfzqVFXl2JFcYAVJ2Usvp/mfKlMFMY6733MqJb8rvvMZPiqiOP7FS3Hs66ah2Zw== 2xtreme@PC-2XTREME"
#  become: true
#  loop:
#    - 2xtreme
#    - root
#
#- name: Install htop
#  apt:
#    name:
#      - htop
#      - vim
#      - apache2
#    state: latest
#  become: true
#
#- name: Create config directories if it does not exist
#  file:
#    path: "{{ item.path }}"
#    state: directory
#    owner: "{{ item.owner }}"
#    group: "{{ item.group }}"
#    mode: "{{ item.mode }}"
#    recurse: yes
#  become: yes
#  loop: "{{ dirs }}"

- name: Debug task to test nested
  debug:
    msg: "{{ item[0] }} ---> {{ item[1] }}"
  with_nested:
    - [ 'alice', 'bob' ]
    - [ 'clientdb', 'employeedb', 'providerdb' ]

- name: Test task with nested
  lineinfile:
    path: "/home/{{ item[0] }}/{{ item[1] }}"
    insertbefore: BOF
    mode: '0640'
    state: present
    owner: "{{ item[0] }}"
    group: "{{ item[0] }}"
    create: yes
    line: |
      {{ item[0] }} ---> {{ item[1] }}
  with_nested:
    - [ 'root', '2xtreme' ]
    - [ 'A', 'B']
  become: true
